### ISSUE TITLE
Sync simulation without defining a clock period runs forever

### ISSUE THREAD

**Issue by korken89** [nmigen/nmigen#522] opened 2020-11-02 13:32 UTC
Hi,

When testing out this framework I ran into the following bug, when running a simulation and forgetting to include the `add_clock`, the simulation runs forever without error.
E.g.

```python
    sim = Simulator(m)
    # sim.add_clock(1e-6) # removing this line causes simulation to run forever
```

I would expect to get an error, instead of the current behavior.

Thanks for a great framework!

**Comment by whitequark** [comment] 2020-11-02 13:54
Duplicate of #442. (I'm well aware that this is a common and frustrating issue--the recent simulator refactoring was intended to make addressing this one easier.)

**Closed by whitequark** 2020-11-02 13:54 UTC
Labels: duplicate

**Comment by korken89** [comment] 2020-11-02 16:41
Thanks, it's known then :)
